apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "app.selectorLabels" . | nindent 4 }}
spec:
  hosts:
  - {{ .Values.ingressAddress | quote}}  
  gateways:
  - {{ .Release.Name }}
  http:
  - route:
    - destination:
        host: {{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: {{ .Values.service.port }}
          
