apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "app.selectorLabels" . | nindent 4 }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https-{{ .Release.Name }}
      protocol: HTTPS
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: etc/istio/ingressgateway-certs/tls.key
    hosts:
    - {{ .Values.ingressAddress | quote}}  
