apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
stringData:
    COSMODB_END_POINT: {{ .Values.secrets.COSMODB_END_POINT | quote }} 
    COSMODB_KEY: {{ .Values.secrets.COSMODB_KEY | quote }}
    COSMODB_MERAAS_NAME: {{ .Values.secrets.COSMODB_MERAAS_NAME | quote }}
    PORT: {{ .Values.secrets.PORT | quote }}
